import type { ScriptMetadata } from '../script-manifest';

export const batchScripts: ScriptMetadata[] = [
  {
    id: 'multi-layer-selector',
    name: '多图层选择器',
    description: '搜索并多选图层，然后一次性选择这些图层中的对象',
    category: 'batch',
    icon: 'layers',
  },
  {
    id: 'move-objects-to-layer',
    name: '移动对象到图层',
    description: '将选中对象移动或复制到指定图层，支持自动创建目标图层',
    category: 'batch',
    icon: 'layers',
    params: [
      {
        name: 'layerName',
        type: 'string',
        label: '目标图层名',
        required: true,
      },
      {
        name: 'action',
        type: 'select',
        label: '操作方式',
        default: 'move',
        options: [
          { value: 'move', label: '移动' },
          { value: 'copy', label: '复制' },
        ],
      },
      {
        name: 'createIfMissing',
        type: 'boolean',
        label: '不存在时自动创建',
        default: true,
      },
      {
        name: 'unlockTargetLayer',
        type: 'boolean',
        label: '自动解锁目标图层',
        default: true,
      },
      {
        name: 'showTargetLayer',
        type: 'boolean',
        label: '自动显示目标图层',
        default: true,
      },
    ],
  },
  {
    id: 'batch-resize',
    name: '智能缩放',
    description: '升级版批量缩放，支持独立宽高、目标尺寸、锚点和描边联动',
    category: 'batch',
    icon: 'resize',
    persistParams: true,
    params: [
      {
        name: 'mode',
        type: 'select',
        label: '缩放模式',
        default: 'scale',
        options: [
          { value: 'scale', label: '按比例' },
          { value: 'size', label: '目标尺寸' },
        ],
      },
      {
        name: 'scaleX',
        type: 'number',
        label: '横向缩放(%)',
        default: 100,
        step: 0.1,
      },
      {
        name: 'scaleY',
        type: 'number',
        label: '纵向缩放(%)',
        default: 100,
        step: 0.1,
      },
      {
        name: 'targetWidth',
        type: 'number',
        label: '目标宽度',
      },
      {
        name: 'targetHeight',
        type: 'number',
        label: '目标高度',
      },
      {
        name: 'lockAspect',
        type: 'boolean',
        label: '保持比例',
        default: true,
      },
      {
        name: 'scaleStrokes',
        type: 'boolean',
        label: '缩放描边',
        default: true,
      },
      {
        name: 'scalePatterns',
        type: 'boolean',
        label: '缩放图案',
        default: true,
      },
      {
        name: 'scaleGradients',
        type: 'boolean',
        label: '缩放渐变',
        default: true,
      },
      {
        name: 'anchor',
        type: 'select',
        label: '锚点',
        default: '5',
        options: [
          { value: '1', label: '左上角' },
          { value: '2', label: '顶部中心' },
          { value: '3', label: '右上角' },
          { value: '4', label: '左侧中心' },
          { value: '5', label: '中心' },
          { value: '6', label: '右侧中心' },
          { value: '7', label: '左下角' },
          { value: '8', label: '底部中心' },
          { value: '9', label: '右下角' },
        ],
      },
    ],
  },
  {
    id: 'data-merge',
    name: '数据合并',
    description: '导入 CSV 数据批量生成设计，支持替换文本、图像和可见性',
    category: 'batch',
    icon: 'database',
  },
  {
    id: 'auto-group-by-intersection',
    name: '智能分组',
    description: '根据对象相交关系自动分组，容差值表示对象间距小于此值时视为相交',
    category: 'batch',
    icon: 'group',
    params: [
      {
        name: 'tolerance',
        type: 'number',
        label: '容差',
        description: '对象间距小于此值时视为相交，0 表示必须接触才分组',
        default: 0,
      },
    ],
  },
  {
    id: 'smart-clone-replace',
    name: '智能克隆/替换',
    description: '将顶部对象克隆到其他对象位置，支持智能对齐和缩放',
    category: 'batch',
    icon: 'copy',
    params: [
      {
        name: 'alignPosition',
        type: 'select',
        label: '对齐位置',
        default: '5',
        options: [
          { value: '1', label: '左上角' },
          { value: '2', label: '顶部中心' },
          { value: '3', label: '右上角' },
          { value: '4', label: '左侧中心' },
          { value: '5', label: '中心' },
          { value: '6', label: '右侧中心' },
          { value: '7', label: '左下角' },
          { value: '8', label: '底部中心' },
          { value: '9', label: '右下角' },
        ],
      },
      {
        name: 'scaleMode',
        type: 'select',
        label: '缩放模式',
        default: 'none',
        options: [
          { value: 'none', label: '不缩放' },
          { value: 'equalCover', label: '等比覆盖（填满目标）' },
          { value: 'equalContain', label: '等比包含（适应目标）' },
          { value: 'equalWidth', label: '等比宽度（匹配宽度）' },
          { value: 'equalHeight', label: '等比高度（匹配高度）' },
          { value: 'targetWidth', label: '仅匹配宽度' },
          { value: 'targetHeight', label: '仅匹配高度' },
        ],
      },
      { name: 'groupPenetrate', type: 'boolean', label: '穿透编组', description: '是否递归处理编组内的对象', default: true },
      { name: 'followRotate', type: 'boolean', label: '跟随旋转', description: '克隆对象是否跟随目标对象的旋转角度', default: true },
      { name: 'syncFill', type: 'boolean', label: '同步填充色', description: '克隆对象是否使用目标对象的填充色', default: false },
      { name: 'syncStroke', type: 'boolean', label: '同步描边', description: '克隆对象是否使用目标对象的描边', default: false },
      { name: 'replaceTarget', type: 'boolean', label: '替换目标对象', description: '克隆完成后删除目标对象', default: false },
      { name: 'groupResult', type: 'boolean', label: '结果编组', description: '将所有克隆对象编组', default: false },
    ],
  },
  {
    id: 'matrix-clone',
    name: '矩阵克隆',
    description: '按行列矩阵克隆对象，支持自定义行列数和间距',
    category: 'batch',
    icon: 'grid',
    params: [
      { name: 'rows', type: 'number', label: '行数', default: 5 },
      { name: 'cols', type: 'number', label: '列数', default: 10 },
      { name: 'rowGap', type: 'number', label: '行间距(mm)', default: 1 },
      { name: 'colGap', type: 'number', label: '列间距(mm)', default: 1 },
    ],
  },
];
