import type { ScriptMetadata } from '../script-manifest';

export const colorScripts: ScriptMetadata[] = [
  {
    id: 'color-notation',
    name: '颜色标注',
    description: '为选中对象添加颜色标注，支持集中放置或分散放置',
    category: 'color',
    icon: 'palette',
    params: [
      {
        name: 'drawBackground',
        type: 'boolean',
        label: '绘制底色和底部信息',
        description: '是否在标注区域绘制背景和汇总信息',
        default: true,
      },
      {
        name: 'centralPlacement',
        type: 'boolean',
        label: '集中放置',
        description: 'true: 画布右上角集中放置；false: 对象附近分别放置',
        default: true,
      },
    ],
  },
  {
    id: 'random-palette-fill',
    name: '随机色卡填充',
    description: '将选中对象随机填充为指定色卡中的颜色，支持输入文档色板名或颜色值。',
    category: 'color',
    icon: 'shuffle',
    persistParams: true,
    params: [
      {
        name: 'palette',
        type: 'textarea',
        label: '色卡',
        description: '每行或用逗号分隔一个颜色。支持文档色板名、#RRGGBB、RGB(r,g,b)、CMYK(c,m,y,k)。',
        default: '主色\n辅色\n#FF6B6B\n#4ECDC4',
        required: true,
      },
      {
        name: 'target',
        type: 'select',
        label: '应用范围',
        default: 'fill',
        options: [
          { value: 'fill', label: '仅填充' },
          { value: 'stroke', label: '仅描边' },
          { value: 'both', label: '填充 + 描边' },
        ],
      },
      {
        name: 'includeGroups',
        type: 'boolean',
        label: '递归处理组内对象',
        default: true,
      },
      {
        name: 'seed',
        type: 'number',
        label: '随机种子',
        description: '相同种子和相同选区顺序会得到稳定结果；留空或 0 则使用当前时间。',
        default: 0,
      },
    ],
  },
  {
    id: 'swap-fill-stroke',
    name: '交换填充/描边颜色',
    description: '交换选中对象的填充色和描边色。',
    category: 'color',
    icon: 'swap',
  },
  {
    id: 'ai-color-generator',
    name: 'AI 色号产生器',
    description: '为印刷 CMYK 四原色及专色生成反字色号标签，支持多种样式与放置选项。',
    category: 'color',
    icon: 'palette',
    persistParams: true,
    params: [
      {
        name: 'cmykMode',
        type: 'select',
        label: 'CMYK 四原色',
        default: 'all',
        options: [
          { value: 'none', label: '无' },
          { value: 'all', label: '全部' },
          { value: 'custom', label: '自定' },
        ],
      },
      { name: 'cmykC', type: 'boolean', label: 'C', default: true },
      { name: 'cmykM', type: 'boolean', label: 'M', default: true },
      { name: 'cmykY', type: 'boolean', label: 'Y', default: true },
      { name: 'cmykK', type: 'boolean', label: 'K', default: true },
      {
        name: 'labelLang',
        type: 'select',
        label: '名称语言',
        default: 'both',
        options: [
          { value: 'both', label: '中英文' },
          { value: 'en', label: '英文' },
          { value: 'zh', label: '中文' },
        ],
      },
      {
        name: 'spotMode',
        type: 'select',
        label: '专色',
        default: 'all',
        options: [
          { value: 'none', label: '无' },
          { value: 'all', label: '全部' },
          { value: 'custom', label: '自定' },
        ],
      },
      {
        name: 'spotNames',
        type: 'textarea',
        label: '自定专色名称',
        description: '每行或用逗号分隔一个专色色板名，例如：871 C, 186 C。找不到时会创建临时专色色板。',
        default: '',
      },
      {
        name: 'simplifyPantone',
        type: 'boolean',
        label: '简化颜色名称',
        default: true,
      },
      {
        name: 'style',
        type: 'select',
        label: '样式',
        default: 'rect',
        options: [
          { value: 'text', label: '字符串排列' },
          { value: 'circle', label: '圆圈反字' },
          { value: 'rect', label: '圆角方块反字' },
        ],
      },
      { name: 'labelWidth', type: 'number', label: '宽 mm', default: 12, min: 1, step: 0.5 },
      { name: 'labelHeight', type: 'number', label: '高 mm', default: 5, min: 1, step: 0.5 },
      { name: 'cornerRadius', type: 'number', label: '半径 mm', default: 1, min: 0, step: 0.5 },
      { name: 'labelGap', type: 'number', label: '色块间距 mm', default: 0, min: 0, step: 0.5 },
      {
        name: 'direction',
        type: 'select',
        label: '方向',
        default: 'h',
        options: [
          { value: 'h', label: '横向' },
          { value: 'v', label: '纵向' },
        ],
      },
      {
        name: 'fontFamily',
        type: 'string',
        label: '字体 PostScript 名',
        default: 'MicrosoftYaHei',
      },
      { name: 'fontSize', type: 'number', label: '字号 mm', default: 3, min: 0.5, step: 0.5 },
      {
        name: 'order',
        type: 'select',
        label: '顺序',
        default: 'cmyk-first',
        options: [
          { value: 'cmyk-first', label: '四色前，专色后' },
          { value: 'spot-first', label: '专色前，四色后' },
        ],
      },
      {
        name: 'placement',
        type: 'select',
        label: '位置',
        default: 'center',
        options: [
          { value: 'center', label: '置于画板正中' },
          { value: 'topleft', label: '置于画板左上角' },
          { value: 'manual', label: '手动黏贴' },
        ],
      },
      { name: 'autoSelect', type: 'boolean', label: '选取', default: true },
      { name: 'groupItems', type: 'boolean', label: '组', default: true },
      { name: 'showInkTotal', type: 'boolean', label: '附加油墨总数', default: false },
      { name: 'convertToOutlines', type: 'boolean', label: '转曲', default: false },
    ],
  },
];
