import type { ScriptMetadata } from '../script-manifest';

export const effectsScripts: ScriptMetadata[] = [
  {
    id: 'graphic-relief',
    name: 'SCD 图形浮雕',
    description: '选择一组水平平行线和上方文字/图形后，将线条穿过图形的位置抬高，生成类似示例图的矢量浮雕线效果。',
    category: 'effects',
    icon: 'vector',
    persistParams: true,
    params: [
      {
        name: 'sourceMode',
        type: 'select',
        label: '来源',
        default: 'panel',
        options: [
          { value: 'panel', label: '面板生成' },
          { value: 'selection', label: '当前选区' },
        ],
      },
      { name: 'text', type: 'string', label: '文字', default: 'SCD' },
      { name: 'fontSize', type: 'number', label: '字号 (pt)', default: 88, min: 4, step: 1 },
      { name: 'fontName', type: 'string', label: '字体 PostScript 名', default: '' },
      { name: 'textX', type: 'range', label: '文字 X', default: 50, min: 0, max: 100, step: 1, suffix: '%' },
      { name: 'textY', type: 'range', label: '文字 Y', default: 45, min: 0, max: 100, step: 1, suffix: '%' },
      { name: 'lineCount', type: 'number', label: '线条行数', default: 64, min: 2, step: 1 },
      { name: 'lineSpacing', type: 'number', label: '行距 (mm)', default: 3.2, min: 0.5, step: 0.1, suffix: 'mm' },
      { name: 'widthPct', type: 'range', label: '线宽范围', default: 88, min: 10, max: 120, step: 1, suffix: '%' },
      { name: 'lineCenterY', type: 'range', label: '线组 Y', default: 55, min: 0, max: 100, step: 1, suffix: '%' },
      {
        name: 'reliefProfile',
        type: 'select',
        label: '浮雕模式',
        default: 'split',
        options: [
          { value: 'split', label: '清晰字形' },
          { value: 'top', label: '上表面' },
        ],
      },
      { name: 'embossStrength', type: 'range', label: '爬升强度', default: 82, min: 0, max: 100, step: 1, suffix: '%' },
      { name: 'clearance', type: 'number', label: '顶面间隙 (mm)', default: 0.8, step: 0.1, suffix: 'mm' },
      { name: 'edgeInset', type: 'number', label: '边缘锐度 (mm)', default: 0.35, min: 0.05, step: 0.05, suffix: 'mm' },
      { name: 'useNative', type: 'boolean', label: 'Native 加速', default: true },
      {
        name: 'quality',
        type: 'select',
        label: '质量/速度',
        default: 'balanced',
        options: [
          { value: 'fast', label: '快速' },
          { value: 'balanced', label: '均衡' },
          { value: 'fine', label: '精细' },
        ],
      },
      { name: 'sampleStep', type: 'number', label: '采样步长 (mm)', default: 0.9, min: 0.3, step: 0.1, suffix: 'mm' },
      { name: 'smoothing', type: 'range', label: '平滑', default: 1, min: 0, max: 8, step: 1 },
      { name: 'curvePrecision', type: 'number', label: '轮廓精度 (mm)', default: 0.8, min: 0.2, step: 0.2, suffix: 'mm' },
      { name: 'lineTolerance', type: 'number', label: '水平容差 (°)', default: 3, min: 0.2, max: 20, step: 0.5, suffix: '°' },
      { name: 'minLineLength', type: 'number', label: '最短线长 (mm)', default: 30, min: 1, step: 1, suffix: 'mm' },
      { name: 'strokeWidth', type: 'number', label: '线宽 (pt)', default: 1, min: 0.1, step: 0.1 },
      { name: 'includeUnchanged', type: 'boolean', label: '保留平直线', default: true },
      { name: 'showTextReference', type: 'boolean', label: '显示淡文字参考', default: false },
      { name: 'customColor', type: 'string', label: '自定义颜色', default: '#29AEEA' },
    ],
  },
  {
    id: 'hexagon-grid',
    name: '六边形网格',
    description: '生成平顶或尖顶六边形网格，支持自动填满画板、散落和等轴线。',
    category: 'effects',
    icon: 'grid',
    persistParams: true,
    params: [
      { name: 'radius', type: 'number', label: '半径', default: 50, min: 1, step: 1 },
      {
        name: 'orientation',
        type: 'select',
        label: '方向',
        default: 'flat',
        options: [
          { value: 'flat', label: '平顶' },
          { value: 'pointy', label: '尖顶' },
        ],
      },
      { name: 'autoFill', type: 'boolean', label: '自动填满画板', default: true },
      { name: 'rows', type: 'number', label: '行数', default: 10, min: 1, step: 1 },
      { name: 'columns', type: 'number', label: '列数', default: 10, min: 1, step: 1 },
      { name: 'scatter', type: 'range', label: '散落比例', default: 0, min: 0, max: 100, step: 1, suffix: '%' },
      { name: 'addIsometric', type: 'boolean', label: '添加等轴线', default: false },
      { name: 'strokeWidth', type: 'number', label: '描边宽度', default: 1, min: 0.1, step: 0.1 },
      { name: 'seed', type: 'number', label: '随机种子', default: 1, step: 1 },
      { name: 'maxItems', type: 'number', label: '对象上限', default: 3000, min: 1, step: 100 },
    ],
  },
  {
    id: 'vector-halftone',
    name: '矢量半调',
    description: '在当前画板中心生成可调密度、形状、方向和随机移除的矢量半调图案。',
    category: 'effects',
    icon: 'shape-circle',
    persistParams: true,
    params: [
      { name: 'width', type: 'number', label: '区域宽度', default: 800, min: 1, step: 10 },
      { name: 'height', type: 'number', label: '区域高度', default: 600, min: 1, step: 10 },
      {
        name: 'shape',
        type: 'select',
        label: '点形状',
        default: 'circle',
        options: [
          { value: 'circle', label: '圆点' },
          { value: 'square', label: '方点' },
        ],
      },
      {
        name: 'mode',
        type: 'select',
        label: '渐变模式',
        default: 'linear',
        options: [
          { value: 'linear', label: '线性' },
          { value: 'radial', label: '径向' },
        ],
      },
      { name: 'density', type: 'range', label: '密度', default: 30, min: 2, max: 150, step: 1 },
      { name: 'ratio', type: 'number', label: '大小比例', default: 0.8, min: 0.01, step: 0.05 },
      { name: 'gradientAngle', type: 'number', label: '渐变角度', default: 90, step: 5, suffix: '°' },
      { name: 'patternRotation', type: 'number', label: '图案旋转', default: 0, step: 5, suffix: '°' },
      { name: 'randomRemove', type: 'range', label: '随机移除', default: 0, min: 0, max: 95, step: 1, suffix: '%' },
      { name: 'seed', type: 'number', label: '随机种子', default: 1, step: 1 },
      { name: 'maxItems', type: 'number', label: '对象上限', default: 8000, min: 1, step: 500 },
    ],
  },
  {
    id: 'perlin-flow',
    name: 'Perlin 有机扰动',
    description: '用 Simplex/Perlin 噪声给选中对象添加灰度、透明度、位移、旋转和缩放变化。',
    category: 'effects',
    icon: 'shuffle',
    persistParams: true,
    params: [
      { name: 'density', type: 'number', label: '噪声密度', default: 5, min: 0.1, step: 0.5 },
      { name: 'seed', type: 'number', label: '随机种子', default: 1, step: 1 },
      { name: 'fillGray', type: 'boolean', label: '灰度填充', default: true },
      { name: 'opacity', type: 'boolean', label: '透明度变化', default: false },
      { name: 'opacityMin', type: 'number', label: '最小透明度', default: 20, min: 0, max: 100, step: 1 },
      { name: 'opacityMax', type: 'number', label: '最大透明度', default: 100, min: 0, max: 100, step: 1 },
      { name: 'position', type: 'boolean', label: '位置扰动', default: false },
      { name: 'offsetX', type: 'number', label: 'X 位移幅度', default: 20, step: 1 },
      { name: 'offsetY', type: 'number', label: 'Y 位移幅度', default: 20, step: 1 },
      { name: 'rotation', type: 'boolean', label: '旋转扰动', default: false },
      { name: 'rotationMin', type: 'number', label: '最小旋转', default: -30, step: 1, suffix: '°' },
      { name: 'rotationMax', type: 'number', label: '最大旋转', default: 30, step: 1, suffix: '°' },
      { name: 'scale', type: 'boolean', label: '缩放扰动', default: false },
      { name: 'scaleMin', type: 'number', label: '最小缩放 (%)', default: 80, step: 1 },
      { name: 'scaleMax', type: 'number', label: '最大缩放 (%)', default: 120, step: 1 },
      {
        name: 'scaleMode',
        type: 'select',
        label: '缩放模式',
        default: 'uniform',
        options: [
          { value: 'uniform', label: '等比' },
          { value: 'width', label: '只宽度' },
          { value: 'height', label: '只高度' },
        ],
      },
      { name: 'includeGroups', type: 'boolean', label: '处理组内对象', default: true },
    ],
  },
  {
    id: 'parametric-array',
    name: '参数化阵列',
    description: '在当前画板上生成 Grasshopper 风格的参数化方块阵列，可控制吸引中心、衰减、密度和扰动。',
    category: 'effects',
    icon: 'grid',
    persistParams: true,
    params: [
      {
        name: 'layoutMode',
        type: 'select',
        label: '布局模式',
        default: 'grid',
        options: [
          { value: 'grid', label: '网格场' },
          { value: 'path', label: '沿路径流动' },
        ],
      },
      { name: 'columns', type: 'number', label: '列数', default: 24 },
      { name: 'rows', type: 'number', label: '行数', default: 28 },
      { name: 'maxSizePct', type: 'range', label: '最大尺寸', default: 72, min: 5, max: 220, step: 1, suffix: '%' },
      { name: 'minSizePct', type: 'range', label: '最小尺寸', default: 6, min: 0, max: 100, step: 1, suffix: '%' },
      {
        name: 'itemShape',
        type: 'select',
        label: '元素形状',
        default: 'diamond',
        options: [
          { value: 'diamond', label: '菱形' },
          { value: 'square', label: '方块' },
          { value: 'rounded-square', label: '圆角方块' },
          { value: 'circle', label: '圆形' },
          { value: 'selection', label: '选中对象' },
        ],
      },
      { name: 'centerX', type: 'range', label: '中心 X', default: 24, min: -50, max: 150, step: 1, suffix: '%' },
      { name: 'centerY', type: 'range', label: '中心 Y', default: 72, min: -50, max: 150, step: 1, suffix: '%' },
      {
        name: 'regionMode',
        type: 'select',
        label: '作用区域',
        default: 'custom',
        options: [
          { value: 'custom', label: '自定义区域' },
          { value: 'artboard', label: '整画板' },
          { value: 'selection', label: '选区范围' },
        ],
      },
      {
        name: 'regionShape',
        type: 'select',
        label: '区域形状',
        default: 'ellipse',
        options: [
          { value: 'ellipse', label: '椭圆区域' },
          { value: 'rectangle', label: '矩形区域' },
          { value: 'diamond', label: '菱形区域' },
        ],
      },
      { name: 'regionWidthPct', type: 'range', label: '区域宽度', default: 68, min: 10, max: 220, step: 1, suffix: '%' },
      { name: 'regionHeightPct', type: 'range', label: '区域高度', default: 72, min: 10, max: 220, step: 1, suffix: '%' },
      {
        name: 'fieldSource',
        type: 'select',
        label: '参数场来源',
        default: 'center',
        options: [
          { value: 'center', label: '单中心' },
          { value: 'selection-centers', label: '选区中心点' },
          { value: 'custom-points', label: '自定义点集' },
        ],
      },
      {
        name: 'maskSource',
        type: 'select',
        label: '路径约束',
        default: 'none',
        options: [
          { value: 'none', label: '无' },
          { value: 'selection-closed', label: '选区闭合路径' },
        ],
      },
      {
        name: 'attractors',
        type: 'textarea',
        label: '吸引/排斥点',
        default: '',
        description: '每行一个点：x,y,w。x/y 为画板百分比，w 为权重，负数表示排斥。',
      },
      { name: 'falloff', type: 'range', label: '衰减范围', default: 62, min: 10, max: 180, step: 1, suffix: '%' },
      {
        name: 'sizeCurve',
        type: 'select',
        label: '尺寸曲线',
        default: 'smooth',
        options: [
          { value: 'linear', label: '线性' },
          { value: 'smooth', label: '平滑' },
          { value: 'sharp', label: '锐利' },
        ],
      },
      { name: 'density', type: 'range', label: '保留密度', default: 100, min: 0, max: 100, step: 1, suffix: '%' },
      { name: 'regularity', type: 'range', label: '规律性', default: 88, min: 0, max: 100, step: 1, suffix: '%' },
      { name: 'jitter', type: 'range', label: '随机扰动', default: 0, min: 0, max: 100, step: 1, suffix: '%' },
      {
        name: 'rotationMode',
        type: 'select',
        label: '旋转模式',
        default: 'uniform',
        options: [
          { value: 'uniform', label: '统一旋转' },
          { value: 'radial', label: '向心旋转' },
          { value: 'random', label: '随机旋转' },
        ],
      },
      { name: 'rotation', type: 'number', label: '旋转角度', default: 45 },
      { name: 'rotationJitter', type: 'range', label: '旋转扰动', default: 0, min: 0, max: 180, step: 1, suffix: '°' },
      { name: 'laneGapPct', type: 'range', label: '路径排布间距', default: 110, min: 20, max: 240, step: 1, suffix: '%' },
      { name: 'stretchXPct', type: 'range', label: '横向拉伸', default: 100, min: 20, max: 220, step: 1, suffix: '%' },
      { name: 'stretchYPct', type: 'range', label: '纵向拉伸', default: 100, min: 20, max: 220, step: 1, suffix: '%' },
      { name: 'roundness', type: 'range', label: '圆角强度', default: 8, min: 0, max: 50, step: 1, suffix: '%' },
      { name: 'strokeWidth', type: 'number', label: '描边宽度 (pt)', default: 0.6, step: 0.1 },
      { name: 'gray', type: 'range', label: '灰度', default: 62, min: 0, max: 100, step: 1, suffix: '%' },
      {
        name: 'style',
        type: 'select',
        label: '绘制方式',
        default: 'stroke',
        options: [
          { value: 'stroke', label: '仅描边' },
          { value: 'fill', label: '仅填充' },
          { value: 'both', label: '填充 + 描边' },
        ],
      },
      { name: 'seed', type: 'number', label: '随机种子', default: 1 },
    ],
  },
  {
    id: 'fillinger',
    name: '随机填充',
    description: '使用对象填充形状',
    category: 'effects',
    icon: 'grid',
    params: [
      { name: 'resizeValue', type: 'number', label: '缩放值 (%)', default: 70 },
      { name: 'maxValue', type: 'number', label: '最大大小 (%)', default: 10 },
      { name: 'minValue', type: 'number', label: '最小大小 (%)', default: 4 },
      { name: 'guttersValue', type: 'number', label: '最小距离', default: 0 },
      { name: 'randomRotate', type: 'boolean', label: '随机旋转', default: true },
      { name: 'groupResult', type: 'boolean', label: '执行后编组', default: false },
    ],
  },
  {
    id: 'randomus',
    name: '随机大师',
    description: '强大的随机变换工具 (复杂参数请使用弹窗)',
    category: 'effects',
    icon: 'shuffle',
  },
  {
    id: 'random-irregular-shapes',
    name: 'Blob 形状生成器',
    description: '创建类似 gradients.app 的单个随机有机 blob，可设置边缘、平滑度、渐变/实色/轮廓。',
    category: 'effects',
    icon: 'shape-circle',
    persistParams: true,
    params: [
      { name: 'edges', type: 'range', label: '边缘', default: 8, min: 3, max: 32, step: 1 },
      { name: 'smoothness', type: 'range', label: '平滑度', default: 70, min: 0, max: 100, step: 1, suffix: '%' },
      { name: 'irregularity', type: 'range', label: '不规则度', default: 48, min: 0, max: 100, step: 1, suffix: '%' },
      { name: 'size', type: 'number', label: '尺寸 (mm)', default: 80, min: 1, step: 1 },
      {
        name: 'fillType',
        type: 'select',
        label: '颜色类型',
        default: 'gradient',
        options: [
          { value: 'gradient', label: '渐变' },
          { value: 'solid', label: '实色' },
          { value: 'outline', label: '轮廓' },
        ],
      },
      { name: 'colorA', type: 'string', label: '颜色 A', default: '#FFA500' },
      { name: 'colorB', type: 'string', label: '颜色 B', default: '#FF6347' },
      { name: 'strokeWidth', type: 'number', label: '轮廓宽度 (pt)', default: 2, min: 0, step: 0.25 },
      {
        name: 'region',
        type: 'select',
        label: '生成位置',
        default: 'artboard',
        options: [
          { value: 'artboard', label: '当前画板中心' },
          { value: 'selection', label: '选区中心' },
        ],
      },
      { name: 'seed', type: 'number', label: '随机种子', default: 914783, min: 0, step: 1 },
    ],
  },
  {
    id: 'replace-items',
    name: '替换对象',
    description: '用选中对象替换其他对象',
    category: 'effects',
    icon: 'swap',
    params: [
      {
        name: 'mode',
        type: 'select',
        label: '替换源',
        default: 'buffer',
        options: [
          { value: 'buffer', label: '剪切板中的对象' },
          { value: 'top_object', label: '顶部对象' },
          { value: 'group_successive', label: '组内连续' },
          { value: 'random', label: '组内随机' },
        ],
      },
      { name: 'ratioPercent', type: 'number', label: '尺寸比例 (%)', default: 100, min: 1, step: 1 },
      { name: 'fitInSize', type: 'boolean', label: '适应大小', default: false },
      { name: 'copyWH', type: 'boolean', label: '复制宽高', default: false },
      { name: 'copyColors', type: 'boolean', label: '复制颜色', default: false },
      { name: 'randomRotate', type: 'boolean', label: '随机旋转', default: false },
      { name: 'saveOriginal', type: 'boolean', label: '保留原对象', default: false },
      { name: 'elementsInAllGroups', type: 'boolean', label: '替换多组选中对象', default: false },
      { name: 'symbolByRegistrationPoint', type: 'boolean', label: '按符号注册点对齐', default: false },
    ],
  },
  {
    id: 'rich-glitch',
    name: '故障艺术',
    description: '生成故障艺术效果',
    category: 'effects',
    icon: 'flash',
    params: [
      { name: 'fragments', type: 'number', label: '片段数量', default: 10 },
      { name: 'offsetX', type: 'number', label: '偏移 X (pt)', default: 5 },
      { name: 'offsetY', type: 'number', label: '偏移 Y (pt)', default: 0 },
      {
        name: 'direction',
        type: 'select',
        label: '方向',
        default: 'horizontal',
        options: [
          { value: 'horizontal', label: '水平 (Horizontal)' },
          { value: 'vertical', label: '垂直 (Vertical)' },
        ],
      },
      { name: 'levels', type: 'number', label: '等级 (Levels)', default: 0 },
    ],
  },
  {
    id: 'metaball',
    name: '融球',
    description: '创建融球效果',
    category: 'effects',
    icon: 'circle',
    params: [
      { name: 'rate', type: 'range', label: '连接率', default: 50, min: 0, max: 100, step: 1, suffix: '%' },
    ],
  },
  {
    id: 'arc-twister',
    name: '弧线扭曲',
    description: '扭曲路径为弧线',
    category: 'effects',
    icon: 'refresh',
  },
  {
    id: 'circumcircle',
    name: '外接圆',
    description: '创建对象的外接圆',
    category: 'effects',
    icon: 'shape-circle',
  },
  {
    id: 'cropulka',
    name: '裁剪工具',
    description: '高级裁剪脚本',
    category: 'effects',
    icon: 'crop',
  },
  {
    id: 'hachures',
    name: '矢量排线',
    description: '为选中对象或当前画板生成矢量排线填充，提供 10 种曲线类型、间距随机、自定义颜色、端点样式等丰富选项。',
    category: 'effects',
    icon: 'shuffle',
    persistParams: true,
    badges: ['Beta'],
    params: [
      {
        name: 'target',
        type: 'select',
        label: '作用范围',
        default: 'selection',
        options: [
          { value: 'selection', label: '当前选区' },
          { value: 'activeArtboard', label: '当前画板' },
        ],
      },
      { name: 'spacing', type: 'number', label: '间距 (mm)', default: 4, min: 0.5, step: 0.5, suffix: 'mm' },
      { name: 'angle', type: 'number', label: '角度 (°)', default: 45, step: 5, suffix: '°' },
      { name: 'thickness', type: 'number', label: '线宽 (mm)', default: 0.5, min: 0.05, step: 0.05, suffix: 'mm' },
      { name: 'spacingJitter', type: 'range', label: '间距随机', default: 0, min: 0, max: 100, step: 5, suffix: '%' },
      {
        name: 'curveType',
        type: 'select',
        label: '曲线类型',
        default: 'A',
        options: [
          { value: 'A', label: 'A 直线' },
          { value: 'B', label: 'B 右端上扬' },
          { value: 'C', label: 'C 中央拱起' },
          { value: 'D', label: 'D 中央下凹' },
          { value: 'E', label: 'E 波峰交错' },
          { value: 'F', label: 'F S 形波浪' },
          { value: 'G', label: 'G 右端上弯' },
          { value: 'H', label: 'H 右端下弯' },
          { value: 'I', label: 'I 左端上引' },
          { value: 'J', label: 'J 左端下引' },
        ],
      },
      { name: 'preserveColor', type: 'boolean', label: '保留原对象颜色', default: false },
      { name: 'customColor', type: 'string', label: '自定义颜色 (hex)', default: '#000000', description: '当未启用「保留原对象颜色」时使用，格式 #RRGGBB。' },
      {
        name: 'strokeCap',
        type: 'select',
        label: '端点样式',
        default: 'butt',
        options: [
          { value: 'butt', label: '平头' },
          { value: 'round', label: '圆头' },
          { value: 'projecting', label: '方头延伸' },
        ],
      },
    ],
  },
];
