import type { ScriptMetadata } from '../script-manifest';

export const effectsScripts: ScriptMetadata[] = [
  {
    id: 'parametric-array',
    name: '参数化阵列',
    description: '在当前画板上生成 Grasshopper 风格的参数化方块阵列，可控制吸引中心、衰减、密度和扰动。',
    category: 'effects',
    icon: 'grid',
    persistParams: true,
    params: [
      {
        name: 'layoutMode',
        type: 'select',
        label: '布局模式',
        default: 'grid',
        options: [
          { value: 'grid', label: '网格场' },
          { value: 'path', label: '沿路径流动' },
        ],
      },
      { name: 'columns', type: 'number', label: '列数', default: 24 },
      { name: 'rows', type: 'number', label: '行数', default: 28 },
      { name: 'maxSizePct', type: 'range', label: '最大尺寸', default: 72, min: 5, max: 220, step: 1, suffix: '%' },
      { name: 'minSizePct', type: 'range', label: '最小尺寸', default: 6, min: 0, max: 100, step: 1, suffix: '%' },
      {
        name: 'itemShape',
        type: 'select',
        label: '元素形状',
        default: 'diamond',
        options: [
          { value: 'diamond', label: '菱形' },
          { value: 'square', label: '方块' },
          { value: 'rounded-square', label: '圆角方块' },
          { value: 'circle', label: '圆形' },
          { value: 'selection', label: '选中对象' },
        ],
      },
      { name: 'centerX', type: 'range', label: '中心 X', default: 24, min: -50, max: 150, step: 1, suffix: '%' },
      { name: 'centerY', type: 'range', label: '中心 Y', default: 72, min: -50, max: 150, step: 1, suffix: '%' },
      {
        name: 'regionMode',
        type: 'select',
        label: '作用区域',
        default: 'custom',
        options: [
          { value: 'custom', label: '自定义区域' },
          { value: 'artboard', label: '整画板' },
          { value: 'selection', label: '选区范围' },
        ],
      },
      {
        name: 'regionShape',
        type: 'select',
        label: '区域形状',
        default: 'ellipse',
        options: [
          { value: 'ellipse', label: '椭圆区域' },
          { value: 'rectangle', label: '矩形区域' },
          { value: 'diamond', label: '菱形区域' },
        ],
      },
      { name: 'regionWidthPct', type: 'range', label: '区域宽度', default: 68, min: 10, max: 220, step: 1, suffix: '%' },
      { name: 'regionHeightPct', type: 'range', label: '区域高度', default: 72, min: 10, max: 220, step: 1, suffix: '%' },
      {
        name: 'fieldSource',
        type: 'select',
        label: '参数场来源',
        default: 'center',
        options: [
          { value: 'center', label: '单中心' },
          { value: 'selection-centers', label: '选区中心点' },
          { value: 'custom-points', label: '自定义点集' },
        ],
      },
      {
        name: 'maskSource',
        type: 'select',
        label: '路径约束',
        default: 'none',
        options: [
          { value: 'none', label: '无' },
          { value: 'selection-closed', label: '选区闭合路径' },
        ],
      },
      {
        name: 'attractors',
        type: 'textarea',
        label: '吸引/排斥点',
        default: '',
        description: '每行一个点：x,y,w。x/y 为画板百分比，w 为权重，负数表示排斥。',
      },
      { name: 'falloff', type: 'range', label: '衰减范围', default: 62, min: 10, max: 180, step: 1, suffix: '%' },
      {
        name: 'sizeCurve',
        type: 'select',
        label: '尺寸曲线',
        default: 'smooth',
        options: [
          { value: 'linear', label: '线性' },
          { value: 'smooth', label: '平滑' },
          { value: 'sharp', label: '锐利' },
        ],
      },
      { name: 'density', type: 'range', label: '保留密度', default: 100, min: 0, max: 100, step: 1, suffix: '%' },
      { name: 'regularity', type: 'range', label: '规律性', default: 88, min: 0, max: 100, step: 1, suffix: '%' },
      { name: 'jitter', type: 'range', label: '随机扰动', default: 0, min: 0, max: 100, step: 1, suffix: '%' },
      {
        name: 'rotationMode',
        type: 'select',
        label: '旋转模式',
        default: 'uniform',
        options: [
          { value: 'uniform', label: '统一旋转' },
          { value: 'radial', label: '向心旋转' },
          { value: 'random', label: '随机旋转' },
        ],
      },
      { name: 'rotation', type: 'number', label: '旋转角度', default: 45 },
      { name: 'rotationJitter', type: 'range', label: '旋转扰动', default: 0, min: 0, max: 180, step: 1, suffix: '°' },
      { name: 'laneGapPct', type: 'range', label: '路径排布间距', default: 110, min: 20, max: 240, step: 1, suffix: '%' },
      { name: 'stretchXPct', type: 'range', label: '横向拉伸', default: 100, min: 20, max: 220, step: 1, suffix: '%' },
      { name: 'stretchYPct', type: 'range', label: '纵向拉伸', default: 100, min: 20, max: 220, step: 1, suffix: '%' },
      { name: 'roundness', type: 'range', label: '圆角强度', default: 8, min: 0, max: 50, step: 1, suffix: '%' },
      { name: 'strokeWidth', type: 'number', label: '描边宽度 (pt)', default: 0.6, step: 0.1 },
      { name: 'gray', type: 'range', label: '灰度', default: 62, min: 0, max: 100, step: 1, suffix: '%' },
      {
        name: 'style',
        type: 'select',
        label: '绘制方式',
        default: 'stroke',
        options: [
          { value: 'stroke', label: '仅描边' },
          { value: 'fill', label: '仅填充' },
          { value: 'both', label: '填充 + 描边' },
        ],
      },
      { name: 'seed', type: 'number', label: '随机种子', default: 1 },
    ],
  },
  {
    id: 'fillinger',
    name: '随机填充',
    description: '使用对象填充形状',
    category: 'effects',
    icon: 'grid',
    params: [
      { name: 'resizeValue', type: 'number', label: '缩放值 (%)', default: 70 },
      { name: 'maxValue', type: 'number', label: '最大大小 (%)', default: 10 },
      { name: 'minValue', type: 'number', label: '最小大小 (%)', default: 4 },
      { name: 'guttersValue', type: 'number', label: '最小距离', default: 0 },
      { name: 'randomRotate', type: 'boolean', label: '随机旋转', default: true },
      { name: 'groupResult', type: 'boolean', label: '执行后编组', default: false },
    ],
  },
  {
    id: 'randomus',
    name: '随机大师',
    description: '强大的随机变换工具 (复杂参数请使用弹窗)',
    category: 'effects',
    icon: 'shuffle',
  },
  {
    id: 'replace-items',
    name: '替换对象',
    description: '用选中对象替换其他对象',
    category: 'effects',
    icon: 'swap',
    params: [
      {
        name: 'mode',
        type: 'select',
        label: '替换源',
        default: 'buffer',
        options: [
          { value: 'buffer', label: '剪切板中的对象' },
          { value: 'top_object', label: '顶部对象' },
          { value: 'random', label: '组内随机' },
        ],
      },
      { name: 'fitInSize', type: 'boolean', label: '适应大小', default: false },
      { name: 'copyWH', type: 'boolean', label: '复制宽高', default: false },
      { name: 'copyColors', type: 'boolean', label: '复制颜色', default: false },
      { name: 'randomRotate', type: 'boolean', label: '随机旋转', default: false },
      { name: 'saveOriginal', type: 'boolean', label: '保留原对象', default: false },
    ],
  },
  {
    id: 'rich-glitch',
    name: '故障艺术',
    description: '生成故障艺术效果',
    category: 'effects',
    icon: 'flash',
    params: [
      { name: 'fragments', type: 'number', label: '片段数量', default: 10 },
      { name: 'offsetX', type: 'number', label: '偏移 X (pt)', default: 5 },
      { name: 'offsetY', type: 'number', label: '偏移 Y (pt)', default: 0 },
      {
        name: 'direction',
        type: 'select',
        label: '方向',
        default: 'horizontal',
        options: [
          { value: 'horizontal', label: '水平 (Horizontal)' },
          { value: 'vertical', label: '垂直 (Vertical)' },
        ],
      },
      { name: 'levels', type: 'number', label: '等级 (Levels)', default: 0 },
    ],
  },
  {
    id: 'metaball',
    name: '融球',
    description: '创建融球效果',
    category: 'effects',
    icon: 'circle',
    params: [
      { name: 'rate', type: 'range', label: '连接率', default: 50, min: 0, max: 100, step: 1, suffix: '%' },
    ],
  },
  {
    id: 'arc-twister',
    name: '弧线扭曲',
    description: '扭曲路径为弧线',
    category: 'effects',
    icon: 'refresh',
  },
  {
    id: 'circumcircle',
    name: '外接圆',
    description: '创建对象的外接圆',
    category: 'effects',
    icon: 'shape-circle',
  },
  {
    id: 'cropulka',
    name: '裁剪工具',
    description: '高级裁剪脚本',
    category: 'effects',
    icon: 'crop',
  },
];
