import type { ScriptMetadata } from '../script-manifest';

export const imagesScripts: ScriptMetadata[] = [
  {
    id: 'image-vectorize',
    name: '图片转矢量',
    description: '读取当前选中的图片，外部面板调整原版位图转矢量参数后应用到 AI。',
    category: 'images',
    icon: 'vector',
    badges: ['Beta'],
    persistParams: true,
    params: [
      { name: 'traceMode', type: 'select', label: '模式', default: 'single', options: [
        { value: 'single', label: '单色' },
        { value: 'multi', label: '多色' },
        { value: 'gradient', label: '渐变' },
      ] },
      { name: 'detailMode', type: 'select', label: '模式切换', default: 'auto', options: [
        { value: 'auto', label: '自动' },
        { value: 'pro', label: '专业' },
      ] },
      { name: 'source', type: 'select', label: '来源', default: 'luminance', options: [
        { value: 'alpha', label: 'Alpha' },
        { value: 'luminance', label: '明度' },
      ] },
      { name: 'autoThreshold', type: 'number', label: '阈值', default: 128, min: 1, max: 254, step: 1 },
      { name: 'autoFilterSize', type: 'number', label: '噪点忽略', default: 6, min: 0, max: 500, step: 1 },
      { name: 'simplifyThreshold', type: 'number', label: '简化锚点阈值', default: 0.5, min: 0, max: 5, step: 0.1 },
      { name: 'strokeDetail', type: 'number', label: '线条粗细', default: 198, min: 0, max: 255, step: 1 },
      { name: 'alphamax', type: 'number', label: '平滑度', default: 1, min: 0, max: 2, step: 0.1 },
      { name: 'opttolerance', type: 'number', label: '精简度', default: 0.2, min: 0, max: 5, step: 0.1 },
      { name: 'turnpolicy', type: 'select', label: '转向策略', default: 'minority', options: [
        { value: 'minority', label: '少数优先' },
        { value: 'majority', label: '多数优先' },
        { value: 'black', label: '黑色优先' },
        { value: 'white', label: '白色优先' },
        { value: 'left', label: '左转优先' },
        { value: 'right', label: '右转优先' },
      ] },
      { name: 'fillColor', type: 'select', label: '图片背景色', default: 'original', options: [
        { value: 'original', label: '原色' },
        { value: 'black', label: '黑色' },
        { value: 'magenta', label: '洋红' },
      ] },
      { name: 'imageBackgroundEnabled', type: 'boolean', label: '图片背景色', default: true },
      { name: 'imageBackgroundColor', type: 'string', label: '背景色', default: '#FFFFFF' },
      { name: 'hierarchical', type: 'select', label: '图层模式', default: 'stacked', options: [
        { value: 'cutout', label: '镂空' },
        { value: 'stacked', label: '堆叠' },
      ] },
      { name: 'filterSpeckle', type: 'number', label: '过滤斑点', default: 8, min: 0, max: 500, step: 1 },
      { name: 'colorPrecision', type: 'number', label: '颜色精度', default: 6, min: 1, max: 8, step: 1 },
      { name: 'targetColors', type: 'number', label: '目标颜色数', default: 17, min: 2, max: 256, step: 1 },
      { name: 'gradientStep', type: 'number', label: '梯度步长', default: 32, min: 1, max: 128, step: 1 },
      { name: 'curveFitting', type: 'select', label: '曲线拟合', default: 'spline', options: [
        { value: 'spline', label: '样条曲线 (Spline)' },
        { value: 'polyline', label: '折线 (Polyline)' },
      ] },
      { name: 'cornerThreshold', type: 'number', label: '拐角平滑', default: 60, min: 0, max: 180, step: 1 },
      { name: 'segmentLength', type: 'number', label: '分段长度', default: 8, min: 1, max: 20, step: 0.5 },
      { name: 'spliceThreshold', type: 'number', label: '拼接阈值', default: 45, min: 0, max: 180, step: 1 },
      { name: 'blendStrength', type: 'number', label: '混合强度', default: 0.48, min: 0, max: 1, step: 0.01 },
      { name: 'preprocessStrength', type: 'number', label: '预处理强度', default: 18, min: 0, max: 100, step: 1 },
      { name: 'edgeThreshold', type: 'number', label: '边缘阈值', default: 107, min: 0, max: 255, step: 1 },
      { name: 'colorTolerance', type: 'number', label: '颜色容差', default: 50, min: 0, max: 255, step: 1 },
      { name: 'minRegionArea', type: 'number', label: '最小区域', default: 260, min: 1, max: 5000, step: 1 },
      { name: 'maxRegions', type: 'number', label: '最大区域数', default: 55, min: 1, max: 512, step: 1 },
      { name: 'maxLayers', type: 'number', label: '最大叠加层', default: 64, min: 0, max: 128, step: 1 },
      { name: 'fitStrictness', type: 'number', label: '拟合严格度', default: 11, min: 0, max: 100, step: 1 },
      { name: 'pathSimplify', type: 'number', label: '路径简化', default: 0.9, min: 0, max: 5, step: 0.1 },
      { name: 'invert', type: 'boolean', label: '黑白反相', default: false },
      { name: 'showAnchors', type: 'boolean', label: '显示锚点', default: true },
      { name: 'optcurve', type: 'boolean', label: '优化贝塞尔曲线', default: true },
      { name: 'autoSimplify', type: 'boolean', label: '自动简化', default: true },
      { name: 'multiPaletteConstraint', type: 'boolean', label: '调色板约束', default: true },
      { name: 'multiCleanEdge', type: 'boolean', label: '清理碎块', default: false },
      { name: 'enableRadial', type: 'boolean', label: '启用径向渐变拟合', default: true },
      { name: 'stackedFriendlyOutput', type: 'boolean', label: '叠层友好输出（减少镂空）', default: false },
    ],
  },
  {
    id: 'embed-images',
    name: '一键嵌入图像',
    description: '将链接图像转换为嵌入',
    category: 'images',
    icon: 'image',
  },
  {
    id: 'inline-svg-to-ai',
    name: '内联 SVG 转 AI',
    description: '将内联 SVG 转换为 AI 对象',
    category: 'images',
    icon: 'code',
    params: [
      { name: 'svgCode', type: 'textarea', label: 'SVG 代码', default: '' },
      { name: 'useOpen', type: 'boolean', label: '通过“打开”插入', default: true },
    ],
  },
  {
    id: 'open-pdf',
    name: '打开 PDF',
    description: '打开 PDF 文件，支持选择页码范围',
    category: 'images',
    icon: 'file-text',
  },
  {
    id: 'ai-enhance',
    name: 'AI 图像增强',
    description: '使用 AI 放大图像、移除背景、降噪处理',
    category: 'images',
    icon: 'sparkle',
  },
];
