import type { ScriptMetadata } from '../script-manifest';

const UNIT_OPTIONS = [
  { value: 'doc', label: '文档单位' },
  { value: 'pt', label: '点 (pt)' },
  { value: 'mm', label: '毫米 (mm)' },
  { value: 'cm', label: '厘米 (cm)' },
  { value: 'm', label: '米 (m)' },
  { value: 'in', label: '英寸 (in)' },
  { value: 'px', label: '像素 (px)' },
];

export const measurementScripts: ScriptMetadata[] = [
  {
    id: 'quick-dimension',
    name: '快速标注尺寸',
    description: '在选中对象左上角添加尺寸标注，使用文档默认单位',
    category: 'measurement',
    icon: 'ruler',
  },
  {
    id: 'measure-path-length',
    name: '测量路径长度',
    description: '计算选中路径的总长度',
    category: 'measurement',
    icon: 'activity',
    params: [
      { name: 'unit', type: 'select', label: '单位', default: 'doc', options: UNIT_OPTIONS },
      { name: 'scale', type: 'number', label: '比例 (1:n)', default: 1, description: '例如：输入100表示1:100' },
      { name: 'digit', type: 'number', label: '小数位数', default: 2 },
    ],
  },
  {
    id: 'make-area',
    name: '面积周长计算',
    description: '计算选中对象的面积和周长',
    category: 'measurement',
    icon: 'square',
    params: [
      { name: 'unit', type: 'select', label: '单位', default: 'doc', options: UNIT_OPTIONS },
      { name: 'scale', type: 'number', label: '比例 (1:n)', default: 1, description: '例如：输入100表示1:100' },
      { name: 'digit', type: 'number', label: '小数位数', default: 3 },
    ],
  },
  {
    id: 'make-size',
    name: '尺寸标注',
    description: '为选中对象添加尺寸标注',
    category: 'measurement',
    icon: 'maximize',
    params: [
      { name: 'top', type: 'boolean', label: '上边', default: true },
      { name: 'left', type: 'boolean', label: '左边', default: true },
      { name: 'bottom', type: 'boolean', label: '下边', default: false },
      { name: 'right', type: 'boolean', label: '右边', default: false },
      {
        name: 'mode',
        type: 'select',
        label: '标注模式',
        default: 'each',
        options: [
          { value: 'each', label: '单体标注' },
          { value: 'between', label: '间距标注' },
          { value: 'entire', label: '总距离标注' },
        ],
      },
      {
        name: 'unitIndex',
        type: 'select',
        label: '单位',
        default: '0',
        options: [
          { value: '0', label: '自动' },
          { value: '1', label: '毫米' },
          { value: '2', label: '厘米' },
          { value: '3', label: '米' },
          { value: '4', label: '点' },
          { value: '5', label: '像素' },
        ],
      },
      { name: 'scale', type: 'number', label: '比例 (1:n)', default: 1, description: '例如：输入100表示1:100' },
      { name: 'decimals', type: 'number', label: '小数位数', default: 2 },
      { name: 'autoSize', type: 'boolean', label: '自动匹配大小', default: true },
      { name: 'fontSize', type: 'number', label: '字号 (pt)', default: 12, description: '关闭自动匹配时使用' },
      { name: 'lineWeight', type: 'number', label: '线条粗细 (pt)', default: 0.5, description: '关闭自动匹配时使用' },
      { name: 'gap', type: 'number', label: '标线距离 (pt)', default: 3, description: '关闭自动匹配时使用' },
      { name: 'doubleLine', type: 'number', label: '界线长度 (pt)', default: 8, description: '关闭自动匹配时使用' },
      { name: 'arrow', type: 'boolean', label: '显示箭头', default: false },
      { name: 'arrowSize', type: 'number', label: '箭头大小 (pt)', default: 6, description: '显示箭头时使用' },
      { name: 'showUnits', type: 'boolean', label: '显示单位后缀', default: true },
    ],
  },
  {
    id: 'create-guides',
    name: '参考线',
    description: '创建出血线、安全线、等分参考线、居中线，支持自定义偏移',
    category: 'measurement',
    icon: 'ruler',
  },
  {
    id: 'count-selected-objects',
    name: '统计对象数量',
    description: '统计选中对象的数量',
    category: 'measurement',
    icon: 'hash',
  },
  {
    id: 'add-crop-marks',
    name: '添加裁切标记',
    description: '在选中对象周围添加裁切标记',
    category: 'measurement',
    icon: 'crop',
    params: [
      { name: 'ratio', type: 'number', label: '比例 (1:X)', default: 1 },
      { name: 'marginMM', type: 'number', label: '边距 (mm)', default: 5 },
      { name: 'dotSizeMM', type: 'number', label: '圆点大小 (mm)', default: 8 },
      { name: 'isConfusion', type: 'boolean', label: '混淆 (底部圆点 50% 偏移)', default: false },
      { name: 'addLShape', type: 'boolean', label: '添加L角线', default: false },
    ],
  },
];
