import type { ScriptMetadata } from '../script-manifest';

export const pathScripts: ScriptMetadata[] = [
  {
    id: 'offset-bleed',
    name: '出血/偏移路径',
    description: '使用 Offset Objects 创建偏移轮廓，支持路径、符号、图片、分组对象及描边/图层选项。',
    category: 'path',
    icon: 'vector',
    persistParams: true,
    params: [
      {
        name: 'offset',
        type: 'number',
        label: '偏移量',
        default: 10,
        step: 0.5,
        description: '正数向外偏移，负数向内偏移。',
      },
      {
        name: 'offsetUnit',
        type: 'select',
        label: '偏移单位',
        default: 'pt',
        options: [
          { value: 'pt', label: 'pt' },
          { value: 'pc', label: 'pc' },
          { value: 'in', label: 'in' },
          { value: 'mm', label: 'mm' },
          { value: 'cm', label: 'cm' },
          { value: 'px', label: 'px' },
        ],
      },
      {
        name: 'join',
        type: 'select',
        label: '转角',
        default: 'miter',
        options: [
          { value: 'miter', label: '斜接' },
          { value: 'round', label: '圆角' },
          { value: 'bevel', label: '斜角' },
        ],
      },
      {
        name: 'miterLimit',
        type: 'number',
        label: '斜接限制',
        default: 4,
        step: 0.5,
      },
      {
        name: 'enableStroke',
        type: 'boolean',
        label: '启用描边',
        default: true,
      },
      {
        name: 'stroke',
        type: 'number',
        label: '描边',
        default: 0.25,
        min: 0,
        step: 0.05,
      },
      {
        name: 'strokeUnit',
        type: 'select',
        label: '描边单位',
        default: 'pt',
        options: [
          { value: 'pt', label: 'pt' },
          { value: 'pc', label: 'pc' },
          { value: 'in', label: 'in' },
          { value: 'mm', label: 'mm' },
          { value: 'cm', label: 'cm' },
          { value: 'px', label: 'px' },
        ],
      },
      {
        name: 'position',
        type: 'select',
        label: '位置',
        default: 'under',
        options: [
          { value: 'under', label: '对象下方' },
          { value: 'above', label: '对象上方' },
        ],
      },
      {
        name: 'container',
        type: 'select',
        label: '容器',
        default: 'newLayer',
        options: [
          { value: 'sameLayer', label: '保持原图层' },
          { value: 'newLayer', label: '移到新图层' },
          { value: 'group', label: '与对象编组' },
        ],
      },
    ],
  },
  {
    id: 'create-boundary',
    name: '创建边界线',
    description: '为选中对象创建矩形边界线（刀版），并自动应用专色。',
    category: 'path',
    icon: 'square',
    params: [
      { name: 'padding', type: 'number', label: '间距 (mm)', default: 0 },
      { name: 'layerName', type: 'string', label: '图层名称', default: '矩形' },
    ],
  },
  {
    id: 'banner-grommets',
    name: '喷绘打扣',
    description: '沿选中对象或画板四边添加打扣圆，支持按数量或间距、快捷四边规则、样式设置、预览和批量画板。',
    category: 'path',
    icon: 'circle',
    persistParams: true,
    params: [
      {
        name: 'target',
        type: 'select',
        label: '作用范围',
        default: 'selectionOrActiveArtboard',
        options: [
          { value: 'selectionOrActiveArtboard', label: '选中对象/当前画板' },
          { value: 'activeArtboard', label: '当前画板' },
          { value: 'allArtboards', label: '所有画板' },
        ],
      },
      {
        name: 'diameter',
        type: 'number',
        label: '圆直径 (mm)',
        default: 8,
        min: 0.1,
        step: 0.5,
      },
      {
        name: 'position',
        type: 'select',
        label: '位置',
        default: 'inside',
        options: [
          { value: 'inside', label: '画面内' },
          { value: 'outside', label: '画面外' },
        ],
      },
      {
        name: 'margin',
        type: 'number',
        label: '距边 (mm)',
        default: 0,
        min: 0,
        step: 0.5,
        description: '在圆刚好贴边的基础上额外内缩或外扩的距离。',
      },
      {
        name: 'countMode',
        type: 'select',
        label: '分布方式',
        default: 'count',
        options: [
          { value: 'count', label: '按数量' },
          { value: 'spacing', label: '按间距' },
        ],
      },
      {
        name: 'spacing',
        type: 'number',
        label: '间距 (mm)',
        default: 500,
        min: 1,
        step: 10,
        description: '按间距模式下自动计算每条边数量，并保留两端角点。',
      },
      {
        name: 'countPreset',
        type: 'select',
        label: '数量规则',
        default: 'custom',
        options: [
          { value: 'custom', label: '分别设置' },
          { value: 'allSame', label: '四边相同' },
          { value: 'horizontalVertical', label: '上下/左右' },
          { value: 'topBottomOnly', label: '只打上下' },
          { value: 'leftRightOnly', label: '只打左右' },
        ],
      },
      {
        name: 'commonCount',
        type: 'number',
        label: '四边数量',
        default: 5,
        min: 0,
        step: 1,
      },
      {
        name: 'horizontalCount',
        type: 'number',
        label: '上下数量',
        default: 5,
        min: 0,
        step: 1,
      },
      {
        name: 'verticalCount',
        type: 'number',
        label: '左右数量',
        default: 4,
        min: 0,
        step: 1,
      },
      {
        name: 'topCount',
        type: 'number',
        label: '上边数量',
        default: 5,
        min: 0,
        step: 1,
      },
      {
        name: 'rightCount',
        type: 'number',
        label: '右边数量',
        default: 4,
        min: 0,
        step: 1,
      },
      {
        name: 'bottomCount',
        type: 'number',
        label: '下边数量',
        default: 5,
        min: 0,
        step: 1,
      },
      {
        name: 'leftCount',
        type: 'number',
        label: '左边数量',
        default: 4,
        min: 0,
        step: 1,
      },
      {
        name: 'appearance',
        type: 'select',
        label: '圆样式',
        default: 'fill',
        options: [
          { value: 'fill', label: '实心圆' },
          { value: 'stroke', label: '空心圆' },
          { value: 'fillStroke', label: '填充+描边' },
        ],
      },
      {
        name: 'colorPreset',
        type: 'select',
        label: '颜色',
        default: 'black',
        options: [
          { value: 'black', label: '黑色' },
          { value: 'white', label: '白色' },
          { value: 'customCmyk', label: '自定义 CMYK' },
        ],
      },
      {
        name: 'strokeWidth',
        type: 'number',
        label: '描边宽度 (mm)',
        default: 0.3,
        min: 0,
        step: 0.1,
      },
      {
        name: 'cyan',
        type: 'number',
        label: 'C',
        default: 0,
        min: 0,
        max: 100,
        step: 1,
      },
      {
        name: 'magenta',
        type: 'number',
        label: 'M',
        default: 0,
        min: 0,
        max: 100,
        step: 1,
      },
      {
        name: 'yellow',
        type: 'number',
        label: 'Y',
        default: 0,
        min: 0,
        max: 100,
        step: 1,
      },
      {
        name: 'black',
        type: 'number',
        label: 'K',
        default: 100,
        min: 0,
        max: 100,
        step: 1,
      },
      {
        name: 'layerName',
        type: 'string',
        label: '图层名称',
        default: '喷绘打扣',
      },
    ],
  },
  {
    id: 'make-envelopes-with-tops',
    name: '批量封套变形',
    description: '用最后选择的对象作为内容，分别套入其他选中对象生成封套变形。',
    category: 'path',
    icon: 'vector',
  },
  {
    id: 'extend-along-path',
    name: '沿路径延长',
    description: '将选中的开放路径沿端点切线方向延长指定长度，闭合路径将被跳过。',
    category: 'path',
    icon: 'vector',
    params: [
      {
        name: 'startLength',
        type: 'number',
        label: '起点延长 (mm)',
        default: 10,
        description: '从路径起点沿切线方向向外延长的距离，设为 0 则不延长。',
        min: 0,
        step: 0.5,
        suffix: 'mm',
      },
      {
        name: 'endLength',
        type: 'number',
        label: '终点延长 (mm)',
        default: 10,
        description: '从路径终点沿切线方向向外延长的距离，设为 0 则不延长。',
        min: 0,
        step: 0.5,
        suffix: 'mm',
      },
    ],
  },
];
