import type { ScriptMetadata } from '../script-manifest';

export const textScripts: ScriptMetadata[] = [
  {
    id: 'text-style-rules',
    name: '文字样式规则',
    description: '按精确文本或正则规则给可编辑文字设置不同颜色和字号',
    category: 'text',
    icon: 'text',
  },
  {
    id: 'select-by-font',
    name: '按字体选择文本',
    description: '按字体名称选择文本框，支持选区优先或全文范围',
    category: 'text',
    icon: 'text',
    params: [
      { name: 'fontName', type: 'string', label: '字体名称', required: true },
      {
        name: 'scope',
        type: 'select',
        label: '作用范围',
        default: 'selection',
        options: [
          { value: 'selection', label: '选区优先（无选区则全文）' },
          { value: 'document', label: '整个文档' },
        ],
      },
    ],
  },
  {
    id: 'select-similar-text-frames',
    name: '选择相似文本框',
    description: '以当前选中文本框为参照，按字体、字号、颜色或内容选择相似文本框',
    category: 'text',
    icon: 'text',
    params: [
      {
        name: 'scope',
        type: 'select',
        label: '作用范围',
        default: 'document',
        options: [
          { value: 'selection', label: '选区优先（无选区则全文）' },
          { value: 'document', label: '整个文档' },
        ],
      },
      { name: 'matchFont', type: 'boolean', label: '匹配字体', default: true },
      { name: 'matchSize', type: 'boolean', label: '匹配字号', default: true },
      { name: 'matchColor', type: 'boolean', label: '匹配颜色', default: false },
      { name: 'matchContents', type: 'boolean', label: '匹配内容', default: false },
      { name: 'matchKind', type: 'boolean', label: '匹配文本类型', default: false },
    ],
  },
  {
    id: 'find-replace-text',
    name: '查找替换文本',
    description: '在所有文本框中查找并替换文字',
    category: 'text',
    icon: 'text-replace',
    params: [
      { name: 'find', type: 'string', label: '查找', required: true },
      { name: 'replace', type: 'string', label: '替换为', required: true },
      { name: 'caseSensitive', type: 'boolean', label: '区分大小写', default: false },
      { name: 'wholeWord', type: 'boolean', label: '全词匹配', default: false },
    ],
  },
  {
    id: 'auto-number',
    name: '文本自动编号',
    description: '自动对选中文本进行排序并编号',
    category: 'text',
    icon: 'list-numbers',
    params: [
      { name: 'prefix', type: 'string', label: '前缀' },
      { name: 'suffix', type: 'string', label: '后缀' },
      { name: 'startNum', type: 'string', label: '起始编号', default: '1' },
      { name: 'increment', type: 'number', label: '增量', default: 1 },
      {
        name: 'sortOrder',
        type: 'select',
        label: '排序',
        default: 'row',
        options: [
          { value: 'row', label: 'Z字形（行优先）' },
          { value: 'column', label: 'N字形（列优先）' },
        ],
      },
    ],
  },
  {
    id: 'change-case',
    name: '大小写转换',
    description: '转换字母大小写，或将数字转换为中文数字',
    category: 'text',
    icon: 'text-upper',
    params: [
      {
        name: 'mode',
        type: 'select',
        label: '转换模式',
        default: 'uppercase',
        options: [
          { value: 'uppercase', label: '全部大写 (UPPERCASE)' },
          { value: 'lowercase', label: '全部小写 (lowercase)' },
          { value: 'titlecase', label: '首字母大写 (Title Case)' },
          { value: 'sentencecase', label: '句首大写 (Sentence case)' },
          { value: 'num-cn-capital', label: '数字转中文大写（壹贰叁）' },
          { value: 'num-cn-normal', label: '数字转中文小写（一二三）' },
        ],
      },
    ],
  },
  {
    id: 'auto-fit-text',
    name: '自动适配文本框',
    description: '调整点文本与区域文本的类型',
    category: 'text',
    icon: 'text-fit',
    params: [
      {
        name: 'mode',
        type: 'select',
        label: '模式',
        default: 'point',
        options: [
          { value: 'point', label: '转换为点文本 (Point Text)' },
          { value: 'area', label: '转换为区域文本 (Area Text)' },
        ],
      },
    ],
  },
  {
    id: 'apply-cjk-latin-fonts',
    name: '中英数字字体规则',
    description: '中文字符套用中文字体，英文与数字套用英文字体',
    category: 'text',
    icon: 'text',
    persistParams: true,
    params: [
      { name: 'cjkFont', type: 'string', label: '中文字体', default: 'Microsoft YaHei' },
      { name: 'latinFont', type: 'string', label: '英文数字字体', default: 'Arial' },
      {
        name: 'scope',
        type: 'select',
        label: '作用范围',
        default: 'selection',
        options: [
          { value: 'selection', label: '选区优先（无选区则全文）' },
          { value: 'document', label: '整个文档' },
        ],
      },
      { name: 'stylePunctuation', type: 'boolean', label: '同时处理标点', default: true },
    ],
  },
  {
    id: 'paragraph-layout',
    name: '段落排版',
    description: '统一设置文本对齐、行距、段前段后和首行缩进',
    category: 'text',
    icon: 'text',
    persistParams: true,
    params: [
      {
        name: 'scope',
        type: 'select',
        label: '作用范围',
        default: 'selection',
        options: [
          { value: 'selection', label: '选区优先（无选区则全文）' },
          { value: 'document', label: '整个文档' },
        ],
      },
      {
        name: 'alignment',
        type: 'select',
        label: '对齐方式',
        default: 'preserve',
        options: [
          { value: 'preserve', label: '保持原样' },
          { value: 'left', label: '左对齐' },
          { value: 'center', label: '居中对齐' },
          { value: 'right', label: '右对齐' },
          { value: 'justify', label: '两端对齐' },
        ],
      },
      { name: 'lineSpacingPt', type: 'number', label: '行距(pt)', default: 18, min: 0.1, step: 0.1 },
      { name: 'spaceBeforePt', type: 'number', label: '段前距(pt)', default: 0, min: 0, step: 0.1 },
      { name: 'spaceAfterPt', type: 'number', label: '段后距(pt)', default: 0, min: 0, step: 0.1 },
      {
        name: 'indentMode',
        type: 'select',
        label: '首行缩进模式',
        default: 'chars',
        options: [
          { value: 'chars', label: '按字符倍数（推荐）' },
          { value: 'pt', label: '固定 pt 值' },
        ],
      },
      { name: 'indentChars', type: 'number', label: '缩进字符数', default: 2, min: 0, step: 0.1 },
      { name: 'firstLineIndentPt', type: 'number', label: '首行缩进(pt)', default: 0, step: 0.1 },
      { name: 'applyLineSpacing', type: 'boolean', label: '应用行距', default: false },
      { name: 'applyParagraphSpacing', type: 'boolean', label: '应用段前后', default: false },
      { name: 'applyFirstLineIndent', type: 'boolean', label: '应用首行缩进', default: true },
    ],
  },
  {
    id: 'split-editable-text',
    name: '文字打散（可编辑）',
    description: '将选中文本按字符拆分为独立文本对象，保持可编辑状态',
    category: 'text',
    icon: 'text',
    params: [
      { name: 'keepOriginal', type: 'boolean', label: '保留原文本', default: false },
      { name: 'ignoreWhitespace', type: 'boolean', label: '忽略空白字符', default: true },
    ],
  },
  {
    id: 'merge-editable-text',
    name: '文字合并（可编辑）',
    description: '将拆分后的文本对象按位置重新合并为可编辑文本',
    category: 'text',
    icon: 'text',
    params: [
      { name: 'removeOriginal', type: 'boolean', label: '删除原始碎片', default: true },
      { name: 'inferSpaces', type: 'boolean', label: '自动推断空格', default: true },
      { name: 'lineTolerancePt', type: 'number', label: '行容差(pt, 0=自动)', default: 0 },
    ],
  },
  {
    id: 'format-text',
    name: '文本格式整理',
    description: '标点全半角、引号转换、中西文间距、空格清理等规则自由组合',
    category: 'text',
    icon: 'text',
    persistParams: true,
    params: [
      { name: 'punctToHalf', type: 'boolean', label: '标点转半角', description: '全角标点转半角', default: false, excludes: ['punctToFull'] },
      { name: 'punctToFull', type: 'boolean', label: '标点转全角', description: '半角标点转全角', default: false, excludes: ['punctToHalf'] },
      { name: 'numLetterToHalf', type: 'boolean', label: '数字字母转半角', description: '全角数字字母转半角', default: false },
      { name: 'quoteToCJK', type: 'boolean', label: '引号转中文样式', description: '英文引号转「」样式', default: false, excludes: ['quoteToWestern'] },
      { name: 'quoteToWestern', type: 'boolean', label: '引号转英文样式', description: '中文引号转""样式', default: false, excludes: ['quoteToCJK'] },
      { name: 'spaceAfterHalfPunct', type: 'boolean', label: '半角标点后加空格', description: '例如 a,b -> a, b', default: false },
      { name: 'spaceCJKWestern', type: 'boolean', label: '中西文间加空格', description: '例如 中文abc -> 中文 abc', default: false },
      { name: 'removeSpaceBeforePunct', type: 'boolean', label: '删标点前空格', description: '例如 hello , -> hello,', default: false },
      { name: 'mergeSpaces', type: 'boolean', label: '合并多余空格', description: '连续空格转单空格', default: false },
      { name: 'trimLineWhitespace', type: 'boolean', label: '去行首尾空白', description: '每行 trim', default: false },
      { name: 'mergeEmptyLines', type: 'boolean', label: '合并空行', description: '连续空行转单空行', default: false },
      { name: 'removeAllSpaces', type: 'boolean', label: '删除所有空格', description: '谨慎使用', default: false },
    ],
  },
];
